name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@v1.1.0
        with:
          branch: gh-pages
          folder: doc/out/html
          config_file: doc/dconfig
